name: HeadOwner
main: me.oribuin.headowner.HeadOwner
description: Get the owner of a head.
version: 1.0.0
api-version: "1.14"
author: Oribuin
commands:
  hdreload:
    description: Reload HeadOwner.
    usage: /hdreload